language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer self-update
  - composer update
  
script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php tests